import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
// import "mapbox-gl/dist/mapbox-gl.css";

export const metadata = {
  title: "Rue de Brenilour",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css"
          rel="stylesheet"
        />
      </head> */}
      <body suppressHydrationWarning={true}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
