import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';
import { Nunito, Great_Vibes } from 'next/font/google';

// import "mapbox-gl/dist/mapbox-gl.css";

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});

const greatVibes = Great_Vibes({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-great-vibes',
});

export const metadata = {
  title: 'petite baleine',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${nunito.variable} ${greatVibes.variable} h-full `}
    >
      <body suppressHydrationWarning={true}>
        <Navbar />
        <div className='relative z-20 pt-[110px]'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
